version: '3.8'
services:
  lusci:
    image: eclipse-temurin:21-jre-alpine
    container_name: lusci
    restart: unless-stopped
    volumes:
      - ./lusci.jar:/opt/app/lusci.jar
    command: ["java", "-jar", "/opt/app/lusci.jar"]
    env_file:
      - .env
